blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions / Questions
    url: https://github.com/SrishtiSonam/AtomicBinding/discussions
    about: Please ask general support or discussion questions here.
